### ISSUE TITLE
Internal server error 

### ISSUE THREAD

**Issue by zygisjas** [sanfrancesco/prerendercloud-apache#2]
When I use this piece of code I get internal server error.

"The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error"

**Comment by jotto** [comment]
What do the logs say?

Check out the apache logs, and see if there's a helpful error message in there. Apache can be difficult to configure so if it's not immediately obvious, you can try nginx, or node.js, or https://www.roast.io/ for an all-in-one web host with prerender.cloud built in.

**Comment by zygisjas** [comment]
The error tells: " .htaccess Invalid command 'RequestHeader' perhaps misspeled or defined by module no included in the server configuration

**Comment by jotto** [comment]
Probably missing an Apache module. If that doesn't fix it, might require a different version of Apache or using a different module. May require some trial/error.

I'm a little rusty on Apache configuration, so if you choose to stick with Apache, you'll have to go down this rabbit hole without me.

**Comment by zygisjas** [comment]
> Probably missing an Apache module. If that doesn't fix it, might require a different version of Apache or using a different module. May require some trial/error.
> 
> I'm a little rusty on Apache configuration, so if you choose to stick with Apache, you'll have to go down this rabbit hole without me.

Just fixed it. Ran the command a2enmod headers, worked like a charm. 

And another thing instead of RewriteRule index.html, I had to change it to index.php.

Thank you.
Z
